security:
  basic:
    enabled: false # turn off securing our application endpoints
  user:
    name: asentinel
    password: mypassword

management:
  security:
    enabled: false # turn off securing the actuator endpoints

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
