security:
  basic:
    enabled: false # turn off securing our application endpoints
  user:
    name: asentinel
    password: mypassword

management:
  security:
    enabled: false # turn off securing the actuator endpoints
